[project]
name = "zpp_config"
version = "2.0.0"
description = "Module pour le chargement et la modification de fichier de configuration"
mainfile = "__init__.py"
requires-python = ">=3.6"

[project.metadata]
authors = ["ZephyrOff"]
maintainers = []
readme = "README.md"
license = "MIT License"
license_file = "LICENSE"
keywords = ["config file", "terminal", "zephyroff"]
classifiers = ["Development Status :: 5 - Production/Stable", "Environment :: Console", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3"]
copyright = ""
changelog = "changelog.md"

[project.urls]
changelog = ""
homepage = "https://github.com/ZephyrOff/zpp_config"
documentation = "https://github.com/ZephyrOff/zpp_config"

[project.dependencies]
watchdog = "N.A"
pyyaml = "N.A"
jinja2 = "N.A"
impmagic = "N.A"
zpp_args = "N.A"
zpp_store = "N.A"
zpp_color = "N.A"
Crypto = "N.A"
pycryptodome = "N.A"
Cryptography = "N.A"
toml = "N.A"

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = ["re", "ast", "os", "watchdog", "pyyaml", "jinja2", "impmagic", "zpp_args", "zpp_store", "zpp_color", "Crypto", "pycryptodome", "Cryptography", "toml"]
includes = ["core", "backend"]
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = ['zpp_config = zpp_config:cli']
